# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.16.0
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # ToolSmith — SFT Warm-Start
#
# Colab free-T4 notebook (human-run only; never executed by Claude Code). LoRA SFT on
# Qwen3-4B-Instruct-2507 over the public function-calling corpus (`results/sft_public_data.jsonl`,
# from `scripts/prep_sft_data.py`) plus verified gold trajectories
# (`results/gold_trajectories.jsonl`, from `scripts/generate_gold_trajectories.py`). Teaches the
# exact tool-call JSON format before GRPO (Phase 4) so RL doesn't waste steps learning syntax.
#
# Before running: mount Drive, upload `results/sft_public_data.jsonl` and
# `results/gold_trajectories.jsonl` (or point `DATA_PATHS` at their Drive copies), and set
# `HF_TOKEN` / `WANDB_API_KEY` in the Colab secrets panel.

# %%
# Colab-only setup cell: clone the toolsmith repo and install it editable (matches README's
# Quickstart install method) so later cells can `import toolsmith`, and so relative paths like
# `results/sft_public_data.jsonl` resolve against the cloned repo root. Skip if already cloned.
# %cd /content
# !git clone https://github.com/Rohanjain2312/toolsmith.git
# %cd /content/toolsmith
# %pip install -q -e .

# %%
# Colab-only install cell. Skip if the environment already has these.
# %pip install -q "unsloth @ git+https://github.com/unslothai/unsloth.git" trl wandb datasets bitsandbytes

# %%
import os
from pathlib import Path

import torch
import wandb
from datasets import Dataset, concatenate_datasets, load_dataset
from trl import SFTConfig, SFTTrainer
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template, train_on_responses_only

# %%
# --- Config ---
MAX_SEQ_LENGTH = 2048
LORA_R = 16
LORA_ALPHA = 32
BATCH_SIZE = 2
GRAD_ACCUM_STEPS = 8
NUM_EPOCHS = 2  # 1-2 per plan; drop to 1 if val JSON-validity plateaus early
LEARNING_RATE = 2e-4
SAVE_STEPS = 100
RESUME_FROM_CHECKPOINT = False  # flip to True on every session after the first

# Pre-quantized Unsloth mirror of the non-thinking Instruct variant (avoids <think> blocks).
# Fallback if this 404s on Colab: "unsloth/Qwen3-4B-Instruct-2507" with load_in_4bit=True below
# (bnb quantizes on load instead of using a pre-quantized mirror).
MODEL_NAME = "unsloth/Qwen3-4B-Instruct-2507-unsloth-bnb-4bit"
HF_MODEL_REPO = "rohanjain2312/toolsmith-qwen3-4b"

DRIVE_CHECKPOINT_DIR = "/content/drive/MyDrive/toolsmith-checkpoints/sft_warmstart"
DATA_PATHS = ["results/sft_public_data.jsonl", "results/gold_trajectories.jsonl"]

# %%
# Bridge Colab Secrets (key icon, left sidebar) into env vars the rest of this notebook reads
# directly. Add HF_TOKEN and WANDB_API_KEY there first, then grant this notebook access when
# prompted -- adding a Colab secret does NOT auto-populate os.environ on its own.
from google.colab import userdata  # noqa: E402 (Colab-only import, top-of-cell by design)

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")
os.environ["WANDB_API_KEY"] = userdata.get("WANDB_API_KEY")

# %%
# Mount Drive for checkpoint persistence across Colab sessions.
from google.colab import drive  # noqa: E402 (Colab-only import, top-of-cell by design)

drive.mount("/content/drive")
os.makedirs(DRIVE_CHECKPOINT_DIR, exist_ok=True)

# %%
# --- 1. Load Qwen3-4B-Instruct-2507 in 4-bit ---
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,  # auto-detect
    load_in_4bit=True,
)

# %%
# --- 2. LoRA setup (r=16, alpha=32) ---
model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_R,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha=LORA_ALPHA,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
    use_rslora=False,
    loftq_config=None,
)

tokenizer = get_chat_template(tokenizer, chat_template="qwen3-instruct")


# %%
def _format_example(example: dict) -> dict:
    """Render one {"messages": [...]} row through the Qwen3 chat template into a "text" field."""
    text = tokenizer.apply_chat_template(
        example["messages"], tokenize=False, add_generation_prompt=False
    )
    return {"text": text}


# %%
# --- Load + combine public function-calling data and verified gold trajectories ---
# Both files are pre-generated by scripts/prep_sft_data.py and
# scripts/generate_gold_trajectories.py, each already shaped {"messages": [...], "source": str}.
raw_datasets = [load_dataset("json", data_files=path, split="train") for path in DATA_PATHS]
dataset: Dataset = concatenate_datasets(raw_datasets).shuffle(seed=3407)
dataset = dataset.map(_format_example)

# %%
# --- 3 & 4. SFTTrainer / SFTConfig, checkpointing to Drive ---
wandb.login(key=os.environ["WANDB_API_KEY"])

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    packing=False,
    args=SFTConfig(
        output_dir=DRIVE_CHECKPOINT_DIR,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRAD_ACCUM_STEPS,
        warmup_steps=10,
        num_train_epochs=NUM_EPOCHS,
        learning_rate=LEARNING_RATE,
        lr_scheduler_type="cosine",
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=10,
        optim="adamw_8bit",
        seed=3407,
        report_to="wandb",
        save_strategy="steps",
        save_steps=SAVE_STEPS,
    ),
)

# Mask loss onto assistant responses only (tool results in loss = garbage gradients).
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)

# %%
# --- 5. Train (resumable: flip RESUME_FROM_CHECKPOINT to True on every session after the first) ---
trainer_stats = trainer.train(resume_from_checkpoint=RESUME_FROM_CHECKPOINT)

# %%
# --- Save LoRA adapter + push to HF Hub ---
model.save_pretrained(f"{DRIVE_CHECKPOINT_DIR}/lora_adapter")
tokenizer.save_pretrained(f"{DRIVE_CHECKPOINT_DIR}/lora_adapter")
model.push_to_hub(HF_MODEL_REPO, token=os.environ["HF_TOKEN"])
tokenizer.push_to_hub(HF_MODEL_REPO, token=os.environ["HF_TOKEN"])

# %%
# --- Collect SFT-model trajectories + extract decision points, for 02_grpo_training.py ---
# 02_grpo_training.py requires results/decision_points.jsonl, built from *SFT-model*
# trajectories -- but the only other producer (scripts/collect_trajectories.py) needs a GGUF
# file, and GGUF export (03_export_gguf.py) only happens after GRPO. Doing it here, right after
# training while the model is still loaded, breaks that circular dependency: no GGUF needed.
from toolsmith.data.decision_points import (  # noqa: E402 (Colab-only cell, top-of-cell by design)
    extract_decision_points,
    select_task_subset,
    write_decision_points,
)
from toolsmith.data.taskspec import TaskSpec  # noqa: E402
from toolsmith.env.model import Model  # noqa: E402
from toolsmith.env.runner import run_episode  # noqa: E402


class SftInferenceModel(Model):
    """Adapts the just-trained SFT model as a Model, via plain transformers .generate()
    (greedy) -- not Unsloth's fast_generate/for_inference helpers, since this cell runs once
    and correctness matters more than speed here; see notebook 02's FastGenerateFrozenModel for
    the vLLM-backed equivalent used during actual GRPO rollouts."""

    def generate(self, messages: list[dict], tools: list[dict]) -> str:
        prompt_text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs = tokenizer(prompt_text, return_tensors="pt").to(model.device)
        with torch.no_grad():
            output_ids = model.generate(**inputs, max_new_tokens=512, do_sample=False)
        return tokenizer.decode(
            output_ids[0][inputs["input_ids"].shape[1] :], skip_special_tokens=True
        )


# Smaller than select_task_subset's 700-task default: this runs one episode at a time (no vLLM
# batching) on a free T4, so 700 would be slow. Raise it if your time budget allows -- same kind
# of tunable dial as NUM_EPOCHS/NUM_GENERATIONS above.
DECISION_POINT_TASK_COUNT = 200
DECISION_POINTS_OUTPUT = Path(f"{DRIVE_CHECKPOINT_DIR}/../decision_points.jsonl")

train_specs = [
    spec
    for line in Path("results/tasks.jsonl").read_text().splitlines()
    if line.strip()
    for spec in [TaskSpec.model_validate_json(line)]
    if spec.split == "train"
]
subset = select_task_subset(train_specs, count=DECISION_POINT_TASK_COUNT)

sft_policy = SftInferenceModel()
states = [
    run_episode(
        spec.id, spec.user_prompt, sft_policy, trajectory_dir=Path("/tmp/sft_trajectories")
    )
    for spec in subset
]
points = extract_decision_points(states)
write_decision_points(points, DECISION_POINTS_OUTPUT)
print(
    f"wrote {len(points)} decision points from {len(states)} trajectories "
    f"to {DECISION_POINTS_OUTPUT}"
)
